### ISSUE TITLE
Routing 404

### ISSUE THREAD

**Issue by PercyTuncar** [shadcn/next-template#24]
Why doesn't the route work? I created a services folder and a page.tsx file inside the app folder and when I navigate to that path it gives me a 404 error.

**Comment by PercyTuncar** [comment]
Is there a different way to route with this template?

**Comment by PercyTuncar** [comment]
![image](https://github.com/shadcn-ui/next-template/assets/33427262/0177bc43-cf58-4f2c-8b4c-570370ff6023)

**Comment by swiecki** [comment]
> ![image](https://user-images.githubusercontent.com/33427262/261807900-0177bc43-cf58-4f2c-8b4c-570370ff6023.png)

It seems like you figured it out, but your file should be page.tsx, not pages.tsx =)
